services:
    web:
        build: ./
        command: python manage.py runserver 0.0.0.0:8020
        volumes:
            - static_volume:/app/static
        expose:
            - 8020
        env_file:
            - ./truck_signs_designs/settings/.env
        depends_on:
            - db
    db:
        image: postgres:15
        volumes:
            - postgres_data:/var/lib/postgresql/data/
        ports:
            - 5432:5432
        env_file:
            - ./truck_signs_designs/settings/.env
    nginx:
        build: ./nginx
        volumes:
            - static_volume:/app/static
        ports:
            - 8020:80
        depends_on:
            - web

volumes:
    postgres_data:
    static_volume:
